"""Core PDF sections: cover, methodology, analysis, citations."""
from __future__ import annotations

from datetime import datetime, timezone

from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import PageBreak, Paragraph, Spacer, Table, TableStyle

from reports.pdf_styles import as_list


def append_cover(story, styles, analysis: dict, report_id: str, org_name: str) -> None:
    story.append(Spacer(1, 2 * inch))
    story.append(Paragraph("REGULATORY COMPLIANCE", styles["subtitle"]))
    story.append(Paragraph("AUDIT REPORT", styles["title"]))
    story.append(Spacer(1, 1 * inch))

    rows = [
        ["Organization:", org_name],
        ["Report ID:", report_id],
        ["Date Generated:", datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")],
        ["Risk Level:", analysis.get("risk_level", "UNKNOWN")],
        ["Compliance Score:", f"{analysis.get('compliance_score', 0)} / 100"],
    ]
    table = Table(rows, colWidths=[2 * inch, 4 * inch])
    table.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 12),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
                ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#334155")),
            ]
        )
    )
    story.append(table)
    story.append(PageBreak())


def append_methodology(story, styles) -> None:
    base = styles["base"]
    body = styles["body"]
    bullet = styles["bullet"]
    header = styles["header"]

    story.append(Paragraph("1. Audit Scope & Methodology", header))
    story.append(Paragraph(
        "This report was generated by the Finace Autonomous Compliance Engine using RAG over RBI/NPCI regulations.",
        body,
    ))
    story.append(Paragraph("Key metrics: risk level, compliance score (0-100), and risk flags.", body))
    story.append(Spacer(1, 20))
    story.append(Paragraph("Key Evaluation Metrics:", base["Heading3"]))
    for item in (
        "Risk Level: severity of compliance gaps.",
        "Compliance Score: quantitative adherence (0-100).",
        "Risk Flags: areas requiring remediation.",
    ):
        story.append(Paragraph(f"• <b>{item}</b>", bullet))
    story.append(PageBreak())


def append_executive_summary(story, styles, analysis: dict) -> None:
    header, body = styles["header"], styles["body"]
    story.append(Paragraph("2. Executive Summary & Deep Analysis", header))
    for para in str(analysis.get("explanation", "")).split("\n"):
        if para.strip():
            story.append(Paragraph(para.strip(), body))
    story.append(PageBreak())


def append_risk_section(story, styles, analysis: dict) -> None:
    base, header, body, bullet = styles["base"], styles["header"], styles["body"], styles["bullet"]
    story.append(Paragraph("3. Risk Assessment & Recommendations", header))

    story.append(Paragraph("Identified Risk Flags", base["Heading2"]))
    flags = as_list(analysis.get("risk_flags"))
    if flags:
        for flag in flags:
            story.append(Paragraph(f"• {flag}", bullet))
    else:
        story.append(Paragraph("No immediate risk flags identified.", body))

    story.append(Spacer(1, 20))
    story.append(Paragraph("Remediation Recommendations", base["Heading2"]))
    for rec in as_list(analysis.get("recommendations")) or ["No recommendations provided."]:
        story.append(Paragraph(f"• {rec}", bullet))

    story.append(Spacer(1, 20))
    story.append(Paragraph("Reasoning Steps", base["Heading2"]))
    for step in as_list(analysis.get("reasoning_steps")):
        story.append(Paragraph(f"- {step}", bullet))
    story.append(PageBreak())


def append_citations(story, styles, analysis: dict) -> None:
    base, header, body, bullet, mono = (
        styles["base"], styles["header"], styles["body"], styles["bullet"], styles["mono"]
    )
    story.append(Paragraph("4. Regulatory Citations (Evidence)", header))
    story.append(Paragraph("Clauses retrieved from official regulatory documents.", body))
    story.append(Spacer(1, 10))

    clauses = analysis.get("applicable_clauses", [])
    if isinstance(clauses, list) and clauses:
        for c in clauses[:20]:
            story.append(Paragraph(f"<b>Source:</b> {c.get('source', '')}", base["Heading3"]))
            story.append(Paragraph(f"<b>Section:</b> {c.get('title', 'Clause')}", base["Normal"]))
            story.append(Paragraph(f'"{str(c.get("text", ""))[:1200]}"', mono))
            story.append(Spacer(1, 15))
    else:
        story.append(Paragraph("No specific clauses were cited.", body))

    if analysis.get("superseded_references") or analysis.get("superseded_change_notes"):
        story.append(Spacer(1, 20))
        story.append(Paragraph("Superseded / Legacy Change Notes", base["Heading2"]))
        for ref in as_list(analysis.get("superseded_references")):
            story.append(Paragraph(f"• Reference: {ref}", bullet))
        for note in as_list(analysis.get("superseded_change_notes")):
            story.append(Paragraph(f"• Note: {note}", bullet))
    story.append(PageBreak())


def append_workflow_appendix(story, styles, analysis: dict) -> None:
    base, header, body = styles["base"], styles["header"], styles["body"]
    story.append(Paragraph("Appendix: Full Workflow Interaction Log", header))
    story.append(Paragraph("Complete transcript used to generate this report.", body))
    story.append(Spacer(1, 10))

    workflow_input = analysis.get("workflow_input", {})
    workflow_text = workflow_input.get("text", "") if isinstance(workflow_input, dict) else str(workflow_input or "")
    if not workflow_text:
        story.append(Paragraph("No interaction log provided.", body))
        return

    for line in workflow_text.split("\n"):
        if not line.strip():
            continue
        if line.startswith("User Query:") or line.startswith("AI Response:"):
            story.append(Spacer(1, 10))
            story.append(Paragraph(f"<b>{line.strip()}</b>", base["BodyText"]))
        else:
            story.append(Paragraph(line.strip(), body))
