_AEPS = ["AEPS", "GENERAL"]

AEPS_RULES: list[dict] = [
    {
        "rule_id": "R_AEPS_001_NO_BC_DUE_DILIGENCE",
        "name": "AePS BC Due Diligence Gap",
        "risk_level": "HIGH",
        "categories": _AEPS,
        "patterns": [
            r"\baeps\b.*\b(no|without)\s+(bc|business\s+correspondent)\s+(due\s+diligence|kyc)\b",
            r"\bbusiness\s+correspondent\b.*\bunvetted\b",
        ],
        "requires_any": [
            r"\bbc\s+due\s+diligence\b",
            r"\bbusiness\s+correspondent\b.*\b(kyc|onboard)",
        ],
        "flag": "AePS business correspondent controls not described",
        "recommendation": "Onboard BCs with full due diligence per NPCI AePS guidelines.",
    },
    {
        "rule_id": "R_AEPS_002_BIOMETRIC_WITHOUT_CONSENT",
        "name": "Biometric Use Without Consent",
        "risk_level": "HIGH",
        "categories": _AEPS,
        "patterns": [
            r"\b(fingerprint|biometric|aadhaar)\b.*\bwithout\s+consent\b",
            r"\baeps\b.*\bno\s+consent\b",
        ],
        "requires_any": [
            r"\bconsent\b",
            r"\baadhaar\s+act\b",
            r"\buidai\b",
        ],
        "flag": "AePS biometric capture without documented consent",
        "recommendation": "Capture Aadhaar/biometric consent per UIDAI and NPCI AePS norms.",
    },
    {
        "rule_id": "R_AEPS_003_NO_CASH_DEPOSIT_LIMITS",
        "name": "AePS Cash Deposit Limits Undefined",
        "risk_level": "MEDIUM",
        "categories": _AEPS,
        "patterns": [r"\bcash\s+deposit\b.*\b(no|without)\s+limit\b", r"\baeps\b.*\bunlimited\s+cash\b"],
        "requires_any": [r"\bcash\s+deposit\s+limit\b", r"\bdaily\s+cap\b", r"\bnpci\s+limit\b"],
        "flag": "AePS cash deposit limits not defined",
        "recommendation": "Apply NPCI AePS transaction and cash deposit caps.",
    },
    {
        "rule_id": "R_AEPS_004_NO_DEVICE_HARDENING",
        "name": "AePS Terminal Security Gap",
        "risk_level": "MEDIUM",
        "categories": _AEPS,
        "patterns": [r"\bmicro\s*atm\b.*\b(unsecured|rooted)\b", r"\baeps\b.*\bno\s+device\s+security\b"],
        "requires_any": [r"\bdevice\s+(hardening|binding|attestation)\b", r"\bterminal\s+security\b"],
        "flag": "AePS device / micro-ATM security not described",
        "recommendation": "Harden terminals, device binding, and secure key storage.",
    },
    {
        "rule_id": "R_AEPS_005_OFFUS_AADHAAR",
        "name": "Off-Us Aadhaar Pay Without Agreement",
        "risk_level": "MEDIUM",
        "categories": _AEPS,
        "patterns": [r"\boff[- ]us\b.*\baeps\b.*\bno\s+agreement\b"],
        "requires_any": [r"\boff[- ]us\b.*\b(aeps|aadhaar)\b", r"\binteroperab"],
        "flag": "Off-us AePS settlement agreements unclear",
        "recommendation": "Document NPCI off-us AePS participation agreements.",
    },
    {
        "rule_id": "R_AEPS_006_AGENT_COMMISSION",
        "name": "AePS Agent Commission / BC Mis-Selling",
        "risk_level": "LOW",
        "categories": _AEPS,
        "patterns": [r"\bagent\b.*\bincentive\b.*\bhidden\s+fee\b", r"\bbc\b.*\bmis[- ]sell\b"],
        "requires_any": [r"\btransparent\s+fee\b", r"\bagent\s+commission\b.*\bdisclos"],
        "flag": "AePS agent incentives may drive mis-selling",
        "recommendation": "Disclose BC/agent fees per RBI/NPCI conduct norms.",
    },
    {
        "rule_id": "R_AEPS_007_DAILY_CAP_BC",
        "name": "BC Transaction Cap Exceeded",
        "risk_level": "MEDIUM",
        "categories": _AEPS,
        "patterns": [r"\bbc\b.*\b(unlimited|exceed)\s+transaction\b", r"\baeps\b.*\bno\s+daily\s+cap\b"],
        "requires_any": [r"\bdaily\s+cap\b", r"\bbc\s+limit\b", r"\bnpci\s+cap\b"],
        "flag": "BC/AePS per-day caps not enforced",
        "recommendation": "Apply RBI/NPCI caps on BC-led AePS transactions.",
    },
    {
        "rule_id": "R_AEPS_008_NO_REVERSAL",
        "name": "AePS Failed-Txn Reversal Gap",
        "risk_level": "MEDIUM",
        "categories": _AEPS,
        "patterns": [
            r"\baeps\b.*\b(failed|rejected)\b.*\b(no|without)\s+reversal\b",
            r"\b(no|without)\s+auto\s+reversal\b.*\baeps\b",
        ],
        "requires_any": [
            r"\breversal\b",
            r"\bend[- ]of[- ]day\s+recon\b",
            r"\bsettlement\s+mismatch\b.*\bhandling\b",
        ],
        "flag": "Failed AePS transactions not auto-reversed",
        "recommendation": "Auto-reverse debits for failed AePS transactions same day.",
    },
    {
        "rule_id": "R_AEPS_009_NO_TAT_BANK_NEGLIGENCE",
        "name": "AePS Fraud / Bank Negligence Process",
        "risk_level": "MEDIUM",
        "categories": _AEPS,
        "patterns": [
            r"\baeps\b.*\b(fraud|negligence|dispute)\b.*\b(no|without)\s+(process|claim|reporting)\b",
            r"\b(no|without)\s+bank\s+negligence\s+claim\b",
        ],
        "requires_any": [
            r"\bnegligence\s+claim\b",
            r"\bTAT\b.*\bfraud\b",
            r"\bipb\b",
            r"\bdispute\s+redressal\b.*\baeps\b",
        ],
        "flag": "AePS fraud/negligence claim process not defined",
        "recommendation": "Document claim intake, investigation and negligence TAT.",
    },
]
