_DATA = ["DATA_SECURITY", "GENERAL"]

DATA_SECURITY_RULES: list[dict] = [
    {
        "rule_id": "R_DATA_001_CVV_STORAGE",
        "name": "Storing CVV / Card Data",
        "risk_level": "HIGH",
        "categories": _DATA,
        "patterns": [
            r"\bstore\s+cvv\b",
            r"\b(save|store|keep)\s+card\s+(cvv|pan|data)\b",
            r"\bstoring\s+card\s+details\s+without\s+tokeni[sz]ation\b",
        ],
        "requires_any": [
            r"\btokeni[sz]ation\b",
            r"\bno\s+cvv\s+storage\b",
            r"\btruncat\w*\s+(pan|card)\b",
        ],
        "flag": "Card details stored in plaintext / CVV retained",
        "recommendation": "Never store CVV; tokenize and truncate card data (PCI-DSS).",
    },
    {
        "rule_id": "R_DATA_002_NO_CONSENT_RECORD",
        "name": "No Consent Artifact / Record",
        "risk_level": "MEDIUM",
        "categories": _DATA,
        "patterns": [
            r"\b(no|without)\s+explicit\s+consent\b",
            r"\bconsent\b.*\bnot\s+(captured|recorded|stored|taken)\b",
            r"\bno\s+consent\s+(record|log|artifact)\b",
        ],
        "requires_any": [
            r"\bconsent\s+(capture|record|log|artifact|management)\b",
            r"\bgranular\s+consent\b",
            r"\bconsent\s+lifecycle\b",
        ],
        "flag": "Customer data consent is not recorded",
        "recommendation": "Ask for granular consent and keep a tamper-evident consent record.",
    },
    {
        "rule_id": "R_DATA_003_NO_DATA_LOCALIZATION",
        "name": "Payment Data Not Localized",
        "risk_level": "MEDIUM",
        "categories": _DATA,
        "patterns": [
            r"\b(store|keep|host)\s+data\s+(outside|offshore)\b",
            r"\bdata\b.*\bno\s+locali[sz]ation\b",
            r"\boverseas\s+(storage|servers?)\b.*\bpayment\b",
        ],
        "requires_any": [
            r"\bdata\s+locali[sz]ation\b",
            r"\bstored\s+in\s+india\b",
            r"\bindia\s+(data\s+)?centre\b",
            r"\brbi\s+storage\s+(guideline|circular)\b",
        ],
        "flag": "Payment system data may not be localized to India",
        "recommendation": "Restrict payment data storage to India; document any exception.",
    },
    {
        "rule_id": "R_DATA_004_NO_ENCRYPTION",
        "name": "No Encryption At Rest / Transit",
        "risk_level": "MEDIUM",
        "categories": _DATA,
        "patterns": [
            r"\b(no|without)\s+encrypt\w+\b",
            r"\bplaintext\s+(storage|transmission)\b",
            r"\bunencrypted\b",
        ],
        "requires_any": [
            r"\bencrypt\w+\b",
            r"\baes[- ]256\b",
            r"\btls\b",
            r"\bmasking\b",
        ],
        "flag": "Data encryption for storage/transit not assured",
        "recommendation": "Encrypt sensitive data at rest and in transit with strong algorithms.",
    },
    {
        "rule_id": "R_DATA_005_NO_BREACH_PROCEDURE",
        "name": "Breach Notification Gap",
        "risk_level": "MEDIUM",
        "categories": _DATA,
        "patterns": [
            r"\bbreach\b.*\b(no|without)\s+(notification|reporting|process)\b",
            r"\bnot\s+notified\s+within\s+72\s+hours\b",
            r"\b(no|without)\s+breach\s+response\b",
        ],
        "requires_any": [
            r"\b72\s+hours\b",
            r"\bbreach\s+(response|notification|management)\b",
            r"\bincident\s+notification\b.*\b(cert-in|dpdp|ncip|rbi)\b",
        ],
        "flag": "Data breach notification procedure not defined",
        "recommendation": "Adopt a 72-hour breach notification process per DPDP/security advisories.",
    },
    {
        "rule_id": "R_DATA_006_MINOR_DATA",
        "name": "Processing Children's Data",
        "risk_level": "MEDIUM",
        "categories": _DATA,
        "patterns": [
            r"\b(children|minors|under\s+18)\b.*\bdata\b",
            r"\bcollect\w*\s+data\s+of\s+(children|minors)\b",
            r"\bkid\s+app\b.*\b(no|without)\s+parental\s+consent\b",
        ],
        "requires_any": [
            r"\bparental\s+consent\b",
            r"\bag[e]\s+verification\b",
            r"\bguardian\b",
        ],
        "flag": "Children's data processing without guardian consent",
        "recommendation": "Verify age and obtain verifiable parental consent where required.",
    },
    {
        "rule_id": "R_DATA_007_LOG_DEIDENTIFICATION",
        "name": "Logs Not De-identified",
        "risk_level": "LOW",
        "categories": _DATA,
        "patterns": [
            r"\blog\w*\b.*\b(raw|full|plain)\s+(pii|pan|cvv|data)\b",
            r"\b(no|without)\s+de[- ]?identification\b.*\blog\b",
        ],
        "requires_any": [
            r"\bde[- ]?identi",
            r"\bmask(ing)?\s*(pii|pan)\b",
            r"\btruncat\w*\s*(pii|pan)\b",
        ],
        "flag": "PII in logs not masked / de-identified",
        "recommendation": "Mask PII and card data in logs and audit trails.",
    },
    {
        "rule_id": "R_DATA_008_VULNERABILITY_GAP",
        "name": "Vulnerability / Pen-Test Gap",
        "risk_level": "MEDIUM",
        "categories": _DATA,
        "patterns": [
            r"\b(no|without)\s+(vulnerability\s+(scan|management)|pen[- ]?test|pentest)\b",
            r"\bno\s+periodic\s+security\s+assessment\b",
        ],
        "requires_any": [
            r"\bvulnerability\s+(scan|management)\b",
            r"\bpen[- ]?test\w*\b",
            r"\bbug\s+bounty\b",
            r"\bcert-in\s+(audit|assessment)\b",
        ],
        "flag": "Periodic security assessment / pen-testing not described",
        "recommendation": "Run scheduled vulnerability scans, pen-tests, and remediation.",
    },
]