_IMPS = ["IMPS", "GENERAL"]

IMPS_RULES: list[dict] = [
    {
        "rule_id": "R_IMPS_001_NO_BENEFICIARY_VERIFICATION",
        "name": "IMPS Without Beneficiary Verification",
        "risk_level": "HIGH",
        "categories": _IMPS,
        "patterns": [
            r"\bimps\b.*\b(no|without)\s+beneficiary\s+(verification|validation)\b",
            r"\btransfer\b.*\bwithout\s+confirming\s+beneficiary\b",
        ],
        "requires_any": [
            r"\bbeneficiary\s+(verification|validation|confirmation)\b",
            r"\bmmid\b",
            r"\baccount\s+verification\b",
        ],
        "flag": "IMPS beneficiary checks not described",
        "recommendation": "Verify beneficiary details and cooling period for new payees.",
    },
    {
        "rule_id": "R_IMPS_002_NO_DISPUTE",
        "name": "IMPS Dispute Handling Missing",
        "risk_level": "MEDIUM",
        "categories": _IMPS,
        "patterns": [r"\bimps\b.*\b(no|without)\s+dispute\b", r"\bimps\b.*\bno\s+complaint\b"],
        "requires_any": [r"\bdispute\b", r"\bcomplaint\b", r"\breversal\b", r"\badjustment\b"],
        "flag": "IMPS dispute / reversal process not described",
        "recommendation": "Align with NPCI IMPS dispute and adjustment timelines.",
    },
    {
        "rule_id": "R_IMPS_003_LIMIT_BYPASS",
        "name": "IMPS Transaction Limit Bypass",
        "risk_level": "MEDIUM",
        "categories": _IMPS,
        "patterns": [
            r"\bimps\b.*\b(unlimited|no\s+limit|bypass\s+limit)\b",
            r"\bexceed(s|ing)?\s+imps\s+limit\b",
        ],
        "requires_any": [r"\btransaction\s+limit\b", r"\bdaily\s+cap\b", r"\brbi\s+limit\b"],
        "flag": "IMPS limits may be exceeded or undefined",
        "recommendation": "Publish and enforce RBI/NPCI IMPS per-transaction limits.",
    },
    {
        "rule_id": "R_IMPS_004_NO_MMID_CONTROLS",
        "name": "MMID / Mobile Transfer Controls Missing",
        "risk_level": "LOW",
        "categories": _IMPS,
        "patterns": [r"\bmmid\b.*\b(shared|public)\b", r"\bno\s+mmid\s+controls\b"],
        "requires_any": [r"\bmmid\b.*\b(secure|registered|verified)\b", r"\bmobile\s+banking\s+pin\b"],
        "flag": "MMID or mobile-IMPS controls weak",
        "recommendation": "Secure MMID issuance and tie to registered mobile/device.",
    },
    {
        "rule_id": "R_IMPS_005_247_WITHOUT_FRAUD",
        "name": "24x7 IMPS Without Fraud Monitoring",
        "risk_level": "MEDIUM",
        "categories": _IMPS,
        "patterns": [r"\b24\s*x\s*7\b.*\bimps\b.*\bno\s+fraud\b", r"\bimps\b.*\bround\s+the\s+clock\b.*\bno\s+monitor"],
        "requires_any": [r"\bfraud\s+monitor\b", r"\breal[- ]time\s+alert\b", r"\bimps\b.*\brisk\b"],
        "flag": "24x7 IMPS without real-time fraud monitoring",
        "recommendation": "Monitor IMPS velocity and anomalies 24x7.",
    },
    {
        "rule_id": "R_IMPS_006_IPO_BLOCK",
        "name": "IPO / ASBA IMPS Controls",
        "risk_level": "LOW",
        "categories": _IMPS,
        "patterns": [r"\bipo\b.*\bimps\b.*\bno\s+block\b", r"\basba\b.*\bmanual\b"],
        "requires_any": [r"\basba\b", r"\bipo\s+block\b", r"\bmandate\s+block\b"],
        "flag": "IPO/ASBA blocking via IMPS unclear",
        "recommendation": "Use mandated blocks for IPO ASBA via IMPS where applicable.",
    },
    {
        "rule_id": "R_IMPS_007_SUCCESS_UNKNOWN",
        "name": "IMPS TCC / Reversal Policy Gap",
        "risk_level": "MEDIUM",
        "categories": _IMPS,
        "patterns": [r"\btimeout\b.*\bno\s+reversal\b", r"\bimps\b.*\bambiguous\b.*\bno\s+policy\b"],
        "requires_any": [r"\btcc\b", r"\breversal\s+policy\b", r"\btimeout\s+handling\b"],
        "flag": "IMPS timeout / reversal policy not described",
        "recommendation": "Define TCC and customer communication for pending IMPS.",
    },
    {
        "rule_id": "R_IMPS_008_MMID_EXPIRY",
        "name": "MMID Expiry / Reuse Controls",
        "risk_level": "LOW",
        "categories": _IMPS,
        "patterns": [
            r"\bmmid\b.*\b(expired|expiry|reuse|re[- ]?assignment)\b",
            r"\b(no|without)\s+mmid\s+lifecycle\b",
        ],
        "requires_any": [
            r"\bmmid\s+(lifecycle|expiry|blocking)\b",
            r"\bmmid\s+regeneration\b",
            r"\bcool[- ]off\b.*\bmmid\b",
        ],
        "flag": "MMID deactivation / reuse controls unclear",
        "recommendation": "Deactivate unused MMIDs and apply reuse cool-off periods.",
    },
    {
        "rule_id": "R_IMPS_009_NO_FRAUD_CALL_BACK",
        "name": "IMPS High-Value Call-Back Gap",
        "risk_level": "MEDIUM",
        "categories": _IMPS,
        "patterns": [
            r"\bimps\b.*\bhigh\s+value\b.*\b(no|without)\s+call\b",
            r"\b(no|without)\s+call[- ]back\b.*\b(imps|remittance)\b",
        ],
        "requires_any": [
            r"\bcall[- ]back\b",
            r"\bfraud\s+check\b",
            r"\bsecond\s+factor\b.*\b(confirm|verify)\b",
        ],
        "flag": "High-value IMPS without call-back / confirmation",
        "recommendation": "Add call-back or step-up confirmation for high-value IMPS.",
    },
]
