"""UPI / BHIM / PPI-style deterministic checks."""

_UPI = ["UPI", "GENERAL"]

UPI_RULES: list[dict] = [
    {
        "rule_id": "R_UPI_001_NO_OTP",
        "name": "UPI Without OTP / Step-Up",
        "risk_level": "HIGH",
        "categories": _UPI,
        "patterns": [
            r"\bupi\b.*\b(no|without)\s+(otp|pin|step[- ]?up)\b",
            r"\b(no|without)\s+(otp|pin)\b.*\bupi\b",
            r"\bupi\b.*\bno\s+two[- ]factor\b",
        ],
        "requires_any": [
            r"\botp\b",
            r"\bupi\s+pin\b",
            r"\bstep[- ]?up\b",
            r"\b2fa\b",
            r"\bmfa\b",
        ],
        "flag": "UPI flow described without OTP/PIN/step-up authentication",
        "recommendation": "Enforce NPCI UPI authentication including PIN/OTP per transaction limits.",
    },
    {
        "rule_id": "R_UPI_002_PPI_NO_FULL_KYC",
        "name": "PPI / Wallet Without Full KYC",
        "risk_level": "HIGH",
        "categories": _UPI,
        "patterns": [
            r"\b(ppi|prepaid|wallet)\b.*\b(minimal|no|without)\s+kyc\b",
            r"\bwallet\b.*\bunverified\b",
            r"\bfull\s+kyc\s+not\s+required\b",
        ],
        "requires_any": [
            r"\bfull\s+kyc\b",
            r"\bcomplete\s+kyc\b",
            r"\bminimum\s+kyc\s+limit\b",
            r"\brbi\s+ppi\b",
        ],
        "flag": "PPI/wallet limits may exceed KYC tier",
        "recommendation": "Map wallet limits to RBI PPI KYC tiers and enforce caps.",
    },
    {
        "rule_id": "R_UPI_003_NO_DISPUTE_UDIR",
        "name": "UPI Dispute / UDIR Not Implemented",
        "risk_level": "MEDIUM",
        "categories": _UPI,
        "patterns": [
            r"\bupi\b.*\b(no|without)\s+(dispute|udir|complaint)\b",
            r"\b(no|without)\s+dispute\s+(api|handling)\b.*\bupi\b",
            r"\budir\b.*\bnot\s+(live|implemented)\b",
        ],
        "requires_any": [
            r"\budir\b",
            r"\bdispute\s+(api|resolution|handling)\b",
            r"\bchargeback\b",
            r"\bcomplaint\s+resolution\b",
        ],
        "flag": "UPI dispute / UDIR integration not described",
        "recommendation": "Connect to NPCI UDIR and publish dispute SLAs.",
    },
    {
        "rule_id": "R_UPI_004_MERCHANT_MDR_GAP",
        "name": "Merchant Onboarding / MDR Gap",
        "risk_level": "LOW",
        "categories": _UPI,
        "patterns": [
            r"\bmerchant\b.*\b(no|without)\s+(onboarding|kyc|mdr)\b",
            r"\bmdr\b.*\bnot\s+(disclosed|compliant)\b",
        ],
        "requires_any": [
            r"\bmerchant\s+onboarding\b",
            r"\bmdr\b",
            r"\binterchange\b",
            r"\bmerchant\s+kyc\b",
        ],
        "flag": "Merchant acquiring / MDR controls unclear",
        "recommendation": "Document merchant due diligence and RBI/NPCI MDR compliance.",
    },
    {
        "rule_id": "R_UPI_005_COLLECT_WITHOUT_MANDATE",
        "name": "UPI Collect Without Mandate",
        "risk_level": "MEDIUM",
        "categories": _UPI,
        "patterns": [
            r"\bcollect\b.*\b(no|without)\s+mandate\b",
            r"\bupi\s+collect\b.*\bunauthorized\b",
        ],
        "requires_any": [
            r"\bupi\s+mandate\b",
            r"\bcollect\s+request\b.*\b(consent|authorize)\b",
            r"\bnach\b",
        ],
        "flag": "UPI collect / mandate consent not described",
        "recommendation": "Use signed mandates and customer authorization for collect requests.",
    },
    {
        "rule_id": "R_UPI_006_SELF_ATTESTATION",
        "name": "NPCI Self-Attestation Gap",
        "risk_level": "HIGH",
        "categories": _UPI,
        "patterns": [
            r"\b(no|not|without)\s+(completed|done)\s+self[- ]?attestation\b",
            r"\bself[- ]?attestation\b.*\b(pending|not)\b",
            r"\bnpci\b.*\bnot\s+attested\b",
        ],
        "requires_any": [
            r"\bself[- ]?attestation\b.*\b(complete|done|filed|submitted)\b",
            r"\bnpci\b.*\battest",
        ],
        "flag": "NPCI self-attestation process not completed",
        "recommendation": "Complete NPCI member self-attestation per operating circulars.",
    },
    {
        "rule_id": "R_UPI_007_LITE_WITHOUT_LIMIT",
        "name": "UPI Lite Limit Controls",
        "risk_level": "MEDIUM",
        "categories": _UPI,
        "patterns": [r"\bupi\s+lite\b.*\b(exceed|no)\s+limit\b", r"\blite\b.*\bunrestricted\b"],
        "requires_any": [r"\bupi\s+lite\b.*\blimit\b", r"\blow\s+value\b.*\bcap\b"],
        "flag": "UPI Lite balance/transaction caps unclear",
        "recommendation": "Apply NPCI UPI Lite limits and customer education.",
    },
    {
        "rule_id": "R_UPI_008_QR_STATIC_FRAUD",
        "name": "Static QR / Intent Tampering Risk",
        "risk_level": "MEDIUM",
        "categories": _UPI,
        "patterns": [r"\bstatic\s+qr\b.*\b(no|without)\s+validation\b", r"\bqr\s+swap\b", r"\bintent\s+tamper\b"],
        "requires_any": [r"\bdynamic\s+qr\b", r"\bqr\s+sign", r"\bamount\s+confirmation\b"],
        "flag": "QR/intent fraud controls not described",
        "recommendation": "Use dynamic QR, amount confirmation, and merchant verification.",
    },
    {
        "rule_id": "R_UPI_009_CREDIT_LINE",
        "name": "UPI Credit / Pay-Later Without Disclosure",
        "risk_level": "MEDIUM",
        "categories": _UPI,
        "patterns": [r"\bupi\s+credit\b", r"\bpay\s+later\b.*\bupi\b", r"\bbnpl\b.*\bwithout\s+disclosure\b"],
        "requires_any": [r"\bcredit\s+line\b.*\bdisclos", r"\binterest\b.*\bupi\b", r"\brbi\s+credit\b"],
        "flag": "UPI credit / BNPL disclosure unclear",
        "recommendation": "Disclose credit terms per RBI/NPCI credit-on-UPI norms.",
    },
    {
        "rule_id": "R_UPI_010_INTERNATIONAL",
        "name": "UPI International Without Framework",
        "risk_level": "HIGH",
        "categories": _UPI,
        "patterns": [r"\binternational\s+upi\b", r"\bupi\b.*\bcross[- ]border\b.*\b(live|enabled)\b"],
        "requires_any": [r"\bupi\s+global\b", r"\bnpci\b.*\binternational\b", r"\bforex\b.*\bupi\b"],
        "flag": "International UPI without stated framework",
        "recommendation": "Follow NPCI international UPI and FEMA requirements.",
    },
    {
        "rule_id": "R_UPI_011_SOUND_BOX",
        "name": "Soundbox / VP Device Security",
        "risk_level": "LOW",
        "categories": _UPI,
        "patterns": [r"\bsound\s*box\b.*\bunregistered\b", r"\bvpd\b.*\bno\s+binding\b"],
        "requires_any": [r"\bdevice\s+binding\b", r"\bmerchant\s+device\b.*\bregister\b"],
        "flag": "Merchant soundbox / VP device controls weak",
        "recommendation": "Register and bind merchant devices per NPCI specs.",
    },
    {
        "rule_id": "R_UPI_012_DELEGATED_PAYMENTS",
        "name": "Delegated / Secondary User UPI",
        "risk_level": "MEDIUM",
        "categories": _UPI,
        "patterns": [r"\bdelegate\b.*\bupi\b.*\bno\s+consent\b", r"\bfamily\s+account\b.*\bwithout\s+authorization\b"],
        "requires_any": [r"\bdelegated\s+payment\b", r"\bsecondary\s+user\b.*\bconsent\b"],
        "flag": "Delegated UPI payments without authorization model",
        "recommendation": "Implement NPCI delegated payment consent flows.",
    },
    {
        "rule_id": "R_UPI_013_BATCH_FILE_SECURITY",
        "name": "UPI Batch / Switch File Security",
        "risk_level": "MEDIUM",
        "categories": _UPI,
        "patterns": [
            r"\b(no|without)\s+(sign|signature|encryption)\b.*\b(batch|file)\b",
            r"\bbatch\s+files?\b.*\b(unauth|unsecure|plain)\b",
            r"\b(no|without)\s+file\s+transfer\s+controls\b",
        ],
        "requires_any": [
            r"\bsign\w*\b.*\b(batch|file)\b",
            r"\bencrypted\s+(batch|file)\b",
            r"\bsftp\b",
            r"\bkey\s+management\b.*\b(switch|batch)\b",
        ],
        "flag": "UPI batch / pinpad file integrity controls unclear",
        "recommendation": "Sign and encrypt switch batch files and rotate keys.",
    },
    {
        "rule_id": "R_UPI_014_CREDIT_PUSH_UNVETTED",
        "name": "Credit Push / Beneficiary Pre-Validation",
        "risk_level": "MEDIUM",
        "categories": _UPI,
        "patterns": [
            r"\bcredit[ -]+push\b.*\b(no|without)\s+(validation|verification)\b",
            r"\bpush\s+payment\b.*\bunvetted\s+account\b",
            r"\b(no|without)\s+beneficiary\s+verification\b",
        ],
        "requires_any": [
            r"\bbeneficiary\s+(validation|verification)\b",
            r"\baccount\s+hold\b",
            r"\bfirst\s+time\s+credit\s+check\b",
        ],
        "flag": "Credit-push transactions not pre-validated",
        "recommendation": "Verify beneficiaries and apply holds for fresh credit-push.",
    },
    {
        "rule_id": "R_UPI_015_AUTO_ALIAS_UNCONSENTED",
        "name": "Auto-Linked / Auto-Route UPI IDs",
        "risk_level": "LOW",
        "categories": _UPI,
        "patterns": [
            r"\bauto[ -]link\w*\b.*\b(vpa|account|upi\s+id)\b",
            r"\b(no|without)\s+consent\b.*\b(link|route)\b.*\bupi\b",
        ],
        "requires_any": [
            r"\bexplicit\s+consent\b.*\b(link|route)\b",
            r"\bvpa\s+management\b",
            r"\bdefault\s+debit\s+account\b.*\bchoice\b",
        ],
        "flag": "VPA/account auto-linking or routing without customer consent",
        "recommendation": "Take explicit consent before linking/routing UPI IDs.",
    },
]
